### ISSUE TITLE
How to use IE9 and Edge

### ISSUE THREAD

**Issue by kolodny** [mantoni/min-webdriver#10]
Having `{ "name": "internet explorer", "version": "9" }` in the `.wd-min` file doesn't work. I get the following message in the terminal

```
# internet explorer 9:
POST /wd/hub/session/***************/execute

Unexpected HTTP status: 500 Internal Server Error

transfer-encoding: chunked
date: Mon, 25 Jan 2016 05:12:54 GMT
content-type: application/json;charset=UTF-8
server: monocle/0.35

Response Status Code: 13
Response Message:
    JavaScript error (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 54 milliseconds
    Build info: version: '2.48.0', revision: 'b7b081a', time: '2015-10-07 15:48:56'
    System info: host: 'Sauce-Win7', ip: '172.20.58.200', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_65'
    Driver info: org.openqa.selenium.ie.InternetExplorerDriver
    Capabilities [{browserAttachTimeout=0, enablePersistentHover=true, ie.forceCreateProcessApi=false, pageLoadStrategy=normal, ie.usePerProcessProxy=false, ignoreZoomSetting=false, handlesAlerts=true, version=9, platform=WINDOWS, proxy={proxyAutoconfigUrl=http://127.0.0.1:19876/pac.js, proxyType=pac}, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:24354/, takesScreenshot=true, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=dismiss}]
    Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXcdc0a4a0
```

Here's what I get when I try to use edge `{ "name": "microsoftedge"}`

```
# microsoftedge *:
POST /wd/hub/session/***********************/execute_async

Unexpected HTTP status: 500 Internal Server Error

transfer-encoding: chunked
date: Mon, 25 Jan 2016 05:11:11 GMT
content-type: application/json;charset=UTF-8
server: monocle/0.35

Response Status Code: 13
Response Message:
    not implemented (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 15 milliseconds
    Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
    System info: host: 'WIN-SB3ER6JQ6ME', ip: '172.20.41.43', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_51'
    Driver info: org.openqa.selenium.edge.EdgeDriver
    Capabilities [{acceptSslCerts=true, browserVersion=20.10240.16384.0, platformVersion=10, browserName=MicrosoftEdge, takesScreenshot=true, pageLoadStrategy=normal, takesElementScreenshot=true, platformName=windows, platform=ANY}]
    Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXA0B2EF96
```

Thanks

**Comment by mantoni** [comment]
For IE 9, you might need to provide a "url" property that points to some (empty) website to get the doctype switch activated (see [this section in the README](https://github.com/mantoni/min-webdriver#known-issues-and-solutions). You can try pointing to <http://maxantoni.de/doctype.html> for a quick test.

Regarding MS Edge, I get the same exception. The `not implemented` warning sounds like [it's an issue on the WebDriver implementation](https://support.saucelabs.com/customer/portal/articles/2103514-windows-10-edge-for-automated-testing-has-been-released). @mkautzmann managed to [get it running with a hack](https://github.com/mantoni/min-webdriver/pull/9). Maybe he can help us here?

**Comment by mkautzmann** [comment]
For IE9 look at @mantoni's post above.

Regarding MS Edge you should try setting `asyncPolling` to `false` in your `.min-wd` config file.

This hack should work on MS Edge until they implement `execute_async`.

Let us know if it worked.

**Comment by mantoni** [comment]
I tried with `"asyncPolling": false` with no luck.

**Comment by kolodny** [comment]
ditto with me for `asyncPolling` , I just forgot to include that in the
issue

On Mon, Jan 25, 2016 at 4:27 PM, Maximilian Antoni <notifications@github.com

**Comment by mkautzmann** [comment]
@mantoni @kolodny When using `asyncPolling` does your log include the message below?

```
# microsoftedge *:
POST /wd/hub/session/***********************/execute_async

Unexpected HTTP status: 500 Internal Server Error
```

If that's true then `asyncPolling` is not making any difference. It is meant to use **execute** instead of **execute_async** on MS Edge since it does not support it.

I can check this. I'm setting up a environment for testing with Edge again.

**Comment by kolodny** [comment]
it basically hangs right now. Here's what it looks like in the sauce VM
![image](https://cloud.githubusercontent.com/assets/1187604/12634672/a8920844-c549-11e5-9bd7-8205aa7b9313.png)

**Comment by mantoni** [comment]
Do you still have the issue with both browsers or is the IE 9 case OK now?

**Comment by kolodny** [comment]
IE 9 works now, I'm still having issues with edge

**Comment by mantoni** [comment]
This should no longer be an issue. The [sinon project has Edge configured for SauceLabs](https://github.com/sinonjs/sinon/blob/master/.min-wd). Closing for now.

@kolodny @mkautzmann If you still have trouble with this, I am happy to reopen.
