### ISSUE TITLE
Test run error

### ISSUE THREAD

**Issue by wesleytodd** [mantoni/min-webdriver#11]
```
Response Status Code: 13

Response Message:

    window._webdriver_poll is not a function

    Build info: version: '2.48.0', revision: 'b7b081a', time: '2015-10-07 15:48:56'

    System info: host: 'chef', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'i386', os.version: '3.13.0-32-generic', java.version: '1.8.0_66'

    Driver info: driver.version: unknown

Error: Unexpected HTTP status: 500 Internal Server Error
```

This is when trying to run my mocha tests with mochify in sauce labs via travis, WHEW what a mouthful :)

You can see the build run here: https://travis-ci.org/wesleytodd/nighthawk/builds/105066568

And the project setup here: https://github.com/wesleytodd/nighthawk/tree/travis

Do you happen to know what I am doing wrong?  I think I followed your instructions well, but clearly missed something.

**Comment by mantoni** [comment]
Thanks for the detailed report. Before I look into it any deeper, can you try running the tests with different browsers? I had lots of trouble with Firefox before. Something about this browser seems to be different in the WebDriver context.

**Comment by wesleytodd** [comment]
Tried with chrome, same error.

https://travis-ci.org/wesleytodd/nighthawk/builds/105176804

Also for what it is worth, before posting I had tried with ie11 as well.

**Comment by wesleytodd** [comment]
Don't mean to bother you, as I know you are probably busy, but any direction you can give me on how this works would be helpful. I am willing to dig in and debug it, hopefully with a PR at the end with a fix, but I am a total noob when it comes to testing tools and integration.  So I don't even know how this works, and don't know what to google to start.

**Comment by mantoni** [comment]
Thanks for pinging. I got lost elsewhere. The way I would approach it is by finding the fastest turnaround, ideally fully local or triggering the SauceLabs build in a single browser from your local machine. You can then start with an empty project – which should work – and then start dragging things in from your project, piece by piece, until you find the part that is causing the issue.

Also, there is an option to leave the browser window open in case of a failure in min-webdriver. If you manage to get the webdriver setup locally, you can inspect the browser environment with the Chrome developer tools. Maybe that gives you some pointers.

There is no golden rule here. The function that is missing is an integral part of min-webdriver. For some weird reason, it's either not yet defined or got deleted. Strange issue.

Anyway, thanks for looking into it.

**Comment by wesleytodd** [comment]
I have it running locally now, what is the option to not have it close when it errors?

**Comment by wesleytodd** [comment]
You can ignore that previous message, I figured it out.  Turns out it is because my tests were trying to modify window.location, which is probably not a good test.  Sorry to have bothered you, and thanks for the help!!

**Comment by mantoni** [comment]
:+1:

**Comment by mnichols** [comment]
The problem here is that `client.js` isnt included on the page unless you abide by the browserify plugin. `window._webdriver_poll(...)` and his friend `window._webdriver_manualPoll` are from this file that must be  on the page.

**Comment by wesleytodd** [comment]
It also turns out I needed an html page to point at.  I added that and I was able to get my tests working.  Thanks for the help!
