### ISSUE TITLE
Is there a way to specify test annotations?

### ISSUE THREAD

**Issue by kolodny** [mantoni/min-webdriver#12]
I'm specifically talking about [`Make sure to set a build number, a pass/fail status, and a public, share, or public restricted visibility for every test that runs using the Test Configuration Options.`](https://wiki.saucelabs.com/display/DOCS/Using+Status+Badges+and+the+Browser+Matrix+Widget+to+Monitor+Test+Results#UsingStatusBadgesandtheBrowserMatrixWidgettoMonitorTestResults-SettingUpStatusBadgesforTestResults) since they are needed to get the browser matrix badge to work [`DOCS`](https://wiki.saucelabs.com/display/DOCS/Test+Configuration+Options#TestConfigurationOptions-TestAnnotation)

It's working for me when I use [selenium-webdriver](https://github.com/kolodny/s-test) ![matrix](https://saucelabs.com/browser-matrix/kolodny-s-test.svg)
but not when using [min-wd](https://github.com/kolodny/deact) ![matrix](https://saucelabs.com/browser-matrix/kolodny-deact.svg)

**Comment by mantoni** [comment]
The only supported options are the ones documented in the readme:

> SauceLabs specific options that only apply if sauceLabs is set to true:
>
> - `sauceJobName` sets a custom name for the SauceLabs job. If a package.json file exists in the current directory, this defaults to the package name.
> - `BUILD_VAR` sets the environment variable name that contains a build number to set, e.g. TRAVIS_BUILD_NUMBER.

What would be needed in addition?

**Comment by kolodny** [comment]
`BUILD_VAR` did the trick (as you can see ;) )
