### ISSUE TITLE
Support for shareable .min-wd config available?

### ISSUE THREAD

**Issue by tjunghans** [mantoni/min-webdriver#21]
Hi Max

I did not find anything in the Readme so I'm asking here. Is there support for a .min-wd config that can be shared via multiple projects? What I have in mind is something like [eslint's shareable config](https://eslint.org/docs/developer-guide/shareable-configs) to reduce the maintenance cost. If not, would you be open to a pull request?

Cheers
TJ

**Comment by mantoni** [comment]
Hey! Thanks for the suggestion.

As a quick and dirty solution, there is a the `--wd-file` option to specify a config file. You could point it to `./node_modules/your-shared-config/min-wd.json`.

Having an eslint style extension mechanism would be quite nice. A pull request is very welcome.

**Comment by mantoni** [comment]
Implemented in #24, released in `v2.12.0`.
