### ISSUE TITLE
Request always expect either an error or a valid response

### ISSUE THREAD

**Issue by brokenseal** [mantoni/min-webdriver#22]
Hi Max,
I noticed an issue that happens in rare (and hard to reproduce) circumstances and it in turns causes the `res` object expected at this line https://github.com/mantoni/min-webdriver/blob/master/lib/driver.js#L52 to be undefined, because at this other line https://github.com/mantoni/min-webdriver/blob/master/lib/request.js#L106 only a null error is passed but no real response.

My best guess is that it would be better to create an error also in that case, instead of returning just `callback(null)` therefore returning something like a generic `fail(...)`? What do you think?

**Comment by brokenseal** [comment]
Of course, let me put together a decent one :)

**Comment by mantoni** [comment]
Fixed as per #23 in `v2.11.2`.
