### ISSUE TITLE
how to pass a parameter to saucelabs?

### ISSUE THREAD

**Issue by deezahyn** [mantoni/min-webdriver#6]
Right now, saucelabs is marking the script is finished.  Is there a way for us to pass the "passed" parameter to true

``` 
"passed": true,
```

as discussed in here
https://docs.saucelabs.com/reference/test-configuration/#accepted-keys

**Comment by mantoni** [comment]
I don't understand the use case. Can you elaborate?

**Comment by deezahyn** [comment]
Hi @mantoni !

Right now I'm trying the --wd option.  I'm trying to figure out how to pass the "passed" parameter in saucelab.

Right now here's what I'm seeing in saucelabs:
http://take.ms/cZtgH

Marked as finished, instead of seeing passed or fail:
http://take.ms/KtjLX

**Comment by mantoni** [comment]
Ah, I see. Well, currently this is not implemented, but shouldn't be hard to do. If you could look into it, I'd happily merge a pull request.

The exit code is parsed out here: https://github.com/mantoni/min-webdriver/blob/master/lib/driver.js#L46

Naming the tests would also be nice. E.g. `min-webdriver {project}` would be nice where `{project}` could be the project name from the package.json.

**Comment by deezahyn** [comment]
I'll give it a try, thanks for pointing that out! @mantoni

**Comment by az7arul** [comment]
+1

**Comment by az7arul** [comment]
@mantoni  @deezahyn  I gave it a go here https://github.com/mantoni/min-webdriver/pull/7

**Comment by mantoni** [comment]
This feature is now available in `v2.5.0`. Thanks everyone.

**Comment by mantoni** [comment]
@az7arul @deezahyn `v2.6.0` now defaults the SauceLabs job name to the name in the cwd `package.json`. Your custom config will override that, of cause.

**Comment by az7arul** [comment]
thats better. thanks again.

**Comment by deezahyn** [comment]
thanks @mantoni will try this out, sorry for the late reply.
