### ISSUE TITLE
Support for newer browsers

### ISSUE THREAD

**Issue by mkautzmann** [mantoni/min-webdriver#8]
I'm trying to test code in Microsoft Edge and Android over Sauce Labs using `min-webdriver`, couldn't manage to make it work. 

Chrome, FF, IE and Safari tests pass with no problem though.

I noticed that the `saucelabs` dependency is at version `0.1.1` and version `1.0.1` is already out there. Some thoughts on that? Is this project still active?

**Comment by mantoni** [comment]
Yes, I'm heavily depending on this module myself, but not testing those new browsers yet. Would you be able to look into upgrading saucelabs?

**Comment by mkautzmann** [comment]
OK, I'll take a look.

**Comment by mkautzmann** [comment]
It looks like the problem goes beyond just updating the `saucelabs` package version.

MS Edge Web Driver doesn't handle the `execute_async` method yet, don't know if they'll implement it. We must rely only on the `execute` method an do polling the old way to make it work. I've implemented that locally and I'm testing different scenarios. 

Question: Is `execute_async` indispensable? The only difference for the end user will be that the testing report will not be 100% real-time but the output will be the same.

About Android: The problem is Selendroid, it crashes with the bundled code for some reason I'm still trying to find out. Since the error report from Sauce Labs is pretty vague I'm downloading tools to test Android locally.

**Comment by mantoni** [comment]
Hmm, I would prefer to keep the async execution if possible. Maybe it's available on a future edge driver. How about optional polling? Either via a config, or depending on the browser. Isn't the selenium protocol even telling what the supported features are?

**Comment by mkautzmann** [comment]
I think you're right. An option for polling would suit the current edge driver problem while not changing behavior for every other browser. Still working on the Android problem though.

Maybe a Selendroid's problem already solved, since Sauce Labs still use version `0.12.0` as far as I know. I'll check to see if there is anything `min-webdriver` can do to make it work.

If I manage to reach a good solution I will submit a PR just for the polling option and another if I find anything to do with Android. OK for you?

**Comment by mantoni** [comment]
Absolutely! Thanks a lot :+1:

**Comment by mkautzmann** [comment]
OK, it turns out that the Android problem is  indeed `selendroid` related. 

It seems like it doesn't handle requests more than 64 KiB in length.

After spending some time trying a bunch of workarounds I decided to talk to them. I've already opened an issue at their repo. Let's see what they say. Link: https://github.com/selendroid/selendroid/issues/997

Tomorrow I should be opening a PR about the optional polling we discussed earlier that temporarily fixes MS Edge. 

Is it OK to include an update to the README mentioning the MS Edge situation under the `Known issues and solutions` section?

**Comment by mantoni** [comment]
Yes please. The README should list the new option (whatever the name will be) and note that it's required for edge for the time being.

**Comment by mkautzmann** [comment]
Sent PR about the polling option, please check it carefully when you have time. Let me know if code needs to be changed. 

Also I think we should create a new issue about the Android situation and close this one after the MS Edge situation is solved.
